### ISSUE TITLE
Update the skycoin submodule to 0.25.1

### ISSUE THREAD

**Issue by stdevHan** [skycoin/pyskycoin#120] opened 2019-02-09 21:56 UTC
## Feature description
Update the skycoin submodule to 0.25.1

## Actual Behavior
Submodule tracks `skycoin/skycoin@v0.25.0` .

## Specifications
* Version: 0.25.1
* Platform: all
* Subsystem: all

## Possible Solution
Update the skycoin submodule to 0.25.1

**Comment by olemis** [comment] 2019-02-09 22:00
Updating to `0.25.1` is not enough . C library source code has been moved to `skycoin/libskycoin` . That's what is actually needed

**Comment by olemis** [comment] 2019-02-09 22:11
duplicate of #110

**Closed by olemis** 2019-02-09 22:11 UTC
Labels: stdev, wip
